### ISSUE TITLE
:each breaks after object state change but works fine with arrays

### ISSUE THREAD

**Issue by garuse** [dy/sprae#12]
Updates of object values is breaking :each but works with array updates (flems.io playground example http://tinyurl.com/25skdzrj):

```html
<div id="container">
<div>
    State obj: <div :text="JSON.stringify(obj)"></div>
    Each obj: <div :each="o in obj" :text="o"></div> <!-- this breaks -->
  </div>
  <div>
    Direct obj access:
    <div :text="obj.a"></div>
    <div :text="obj.b"></div>
  </div>
<hr/>
 <div>
    State arr: <div :text="JSON.stringify(arr)"></div>
    Each arr: <br/><div :each="o in arr" :text="o"></div>
  </div>
  <div>
    Direct arr access:
    <div :text="arr[0]"></div>
    <div :text="arr[1]"></div>
  </div>
</div>

<script type="module">
  import sprae from 'https://cdn.jsdelivr.net/npm/sprae/sprae.js'
  const state = sprae(container, {obj: {a:'vala', b:'valb'}, arr: [1,2], JSON: JSON})
  state.obj.a = 'newvala' // :each not working after this
  state.arr[0] = 42
</script>
```
The result is:
```
State obj:
{"a":"newvala","b":"valb"}
Each obj:
Direct obj access:
newvala
valb
------------------------------------
State arr:
[42,2]
Each arr:
42
2
Direct arr access:
42
2
```
and I expected:
```
State obj:
{"a":"newvala","b":"valb"}
Each obj:
newvala
valb
Direct obj access:
newvala
valb
------------------------------------
State arr:
[42,2]
Each arr:
42
2
Direct arr access:
42
2
```

Because of this I am still using petite-vue but I would have preferred sprae instead.
I really appreciate your work, especially the latest performance improvements!
Thank you!

**Comment by dy** [comment]
Thanks for the report. Will have a look

**Comment by dy** [comment]
Thanks for the report! Fixed in 8.1.0

**Comment by garuse** [comment]
> Also: if you add new props to object, they won't be caught up. Lmk if that's something needed.

Indeed that will fit my use case and will be consistent with other frameworks.
Thank you for the quick fix!

**Comment by dy** [comment]
So you need it?

**Comment by garuse** [comment]
Yes I do.
My data comes from an API as an array of objects (json) and I want to
render it in a table format.
I find it strange to convert it to an array of arrays so I better leave it
as an object.

Kind regards!

**Comment by dy** [comment]
You're welcome, try and lmk. 
There's one opportunity of overall perf improvement by reducing API, so possibly major release will be a bit terser but more performant.
