### ISSUE TITLE
Render fragments

### ISSUE THREAD

**Issue by garuse** [dy/sprae#14]
I found a use case that does not seem to be supported by sprae: fragments rendering.

I want to render two table rows at a time, in a loop:
```html
<template :ref="row">
  <tr><td>col1</td><td>col2</td></tr>
  <tr><td :text="data"></td></tr>
</template>
```

I cannot use a single tag as parent because it will break the table structure, so I would like something similar with Alpine:
```html
<template x-for="post in posts">
  <h2 x-text="post.title"></h2>
</template>
```

Is it possible to implement something like this?
```html
<template :each="i in 3" :ref="row" :with="{data: rowdata}"></template>
```
Thank you!

**Comment by dy** [comment]
Thanks for the good use-case. It must be possible. This and also easy declaring components like '<template :define=my-elem'>...</template>' would give another sense to sprae - template directives. Maybe that would allow to deprecate ':render'.

**Comment by dy** [comment]
Ok, done in v9.
