### ISSUE TITLE
Template tag inconsistency using :each/:if

### ISSUE THREAD

**Issue by Swizz** [dy/sprae#20]
Hi, 
Thank you for bringing us Sprae. 

Lately, I have noticed some unlikely behaviors regarding the use of the template tag especially using the :each and :if directives.
Following this given [live example](https://jsbin.com/pegaqikiwo/edit?html,output) .

The :if directive seems not working at all in an :each block but only if this is used inside a template tag.
Even by including syntax error, no errors are shown, that leads me to think that the :if directive is not called at all.

Is this intended behavior ?

**Comment by dy** [comment]
Thanks for report, let me check. There is possible incompleteness of :if :each combo, I haven't yet discovered all possible cases.

**Comment by Swizz** [comment]
I have also notified that directives order is truly important, that might be written in the doc. 

This case will works :
```html
<li :each="value in values" :text="value.name"></li>
```

But this one will raise a `value is not defined` error :
```html
<li :text="value.name" :each="value in values"></li>
```

**Comment by Swizz** [comment]
Thank you for your work. The fix works like a charm.

This is a username I use since 20 years, and I do not remember where it comes ; but I do like how it sounds despite the meaning
