### ISSUE TITLE
CDN version

### ISSUE THREAD

**Issue by vanodevium** [dy/sprae#24]
Are there any plan to make a CDN version of the file so that it can be included with a simple **<script>** tag?

**Comment by dy** [comment]
I used to have it, as sprae.auto.js, but found that not as useful, since almost always UI needs some interaction with state (sooner or later) and it's better to have module version from the beginning. I can reconsider if you have convincing case

**Comment by vanodevium** [comment]
@dy 

If that's enough, I'll just describe my case:
- it is forbidden to use bundlers and builders
- all libraries on the page are included only as the CDN version by simple <script>
- not all of these libraries have a version with **export**

As a result, porridge is obtained, with which you need to fight somehow.

If you'll made a CDN version without automatic **init()**, then everything could be done approximately like this:

1. <script src="CDN/sprae.min.js">
2. DOMContentLoaded
3. state initiation (from the server or another way)
4. **window.Sprae.init()**

**Comment by dy** [comment]
I see what you mean now, an old school `window.sprae` without bundlers/modules etc, like `window.jQuery`.
It creates porridge here though, although to lesser extent.
Yeah, I guess that version could make sense, I can add something like
`<script src="https://unpkg.com/sprae" init/>` - that would cover all non-ESM cases, like global object, require, AMD, etc, also would optionally enable autoinit.

**Comment by vanodevium** [comment]
@dy 

May I ask how long it takes to do this?

I do not want to rush you in any way, just to plan my work.

**Comment by dy** [comment]
Do you need it urgently?
I was thinking to release it likely next minor version, possibly today.

**Comment by vanodevium** [comment]
@dy

It would be very cool!

Because I'm already working on this code right now and I really need **sprae**.

Thanx!

**Comment by dy** [comment]
@vanodevium ok, I'll work on it the next few hours, thanks for the PRs

**Comment by dy** [comment]
Ok, added in v10.9.0

**Comment by vanodevium** [comment]
@dy 

it's WOW, it's awesome! 

Thanx!

> works like a charm
