### ISSUE TITLE
UMD version

### ISSUE THREAD

**Issue by vanodevium** [dy/sprae#28]
![image](https://github.com/user-attachments/assets/77cafbee-82d4-40b5-96f5-5731de0703b9)

Maybe we can add some configuration to avoid this style errors?

**Comment by dy** [comment]
Do you mean just code formatting? It's done via [esbuild-plugin-umd-wrapper](https://github.com/Inqnuam/esbuild-plugin-umd-wrapper), the only way to do that is making an issue there.
Do you expect UMD entry to be readable? I'd anticipate it to be used more as obfuscated `sprae.umd.min.js` with help of sourcemaps.

**Comment by vanodevium** [comment]
@dy 

Yeap, only red lineі in the editor.

It's parseable by browser, so there is some aesthetic question :)

**Comment by dy** [comment]
If you want to post an issue there please do.
But l&f of bundled version is not priority at all here, so I'll close it if you don't mind.

**Comment by vanodevium** [comment]
@dy it's OK
