### ISSUE TITLE
Question: :style directive

### ISSUE THREAD

**Issue by vanodevium** [dy/sprae#29]
Am I correct in understanding that the **:style** directive works with a property like a string?

If so, can we improve the functionality a bit and accept the **camelCase** objects keys and automatically insert the **kebab-case**?

**Comment by dy** [comment]
Can you give an example?

**Comment by vanodevium** [comment]
@dy 
Of course

```
<header class="navbar is-flex p-0 pt-2 pb-2"
        :style="{
          color: '{{$c->fontColorify('header-font-color')}}',
          backgroundColor: '{{$c->backgroundColorify('header-background-color')}}'
        }"
>
...
</header>
```

This code didn't set **background-color**

**Comment by dy** [comment]
Thanks, done!
