### ISSUE TITLE
Having an `:if` without an `:else` causes the subsequent sibling element to have no text content.

### ISSUE THREAD

**Issue by jaymanmatthewsdev** [dy/sprae#3]
What the title says.

![image](https://user-images.githubusercontent.com/108161206/204345626-508817f7-2ea7-4957-bc0c-0be63aae43d9.png)

The first button has no text content and does nothing in this example.

Thanks heaps!

P.S. I am really really loving this library - more than Alpine already! I hope to see a lot more from it. Kudos

**Comment by dy** [comment]
Thanks for the feedback, I appreciate! 
Fixed in v2.1.2
