### ISSUE TITLE
Just question: directives priority

### ISSUE THREAD

**Issue by vanodevium** [dy/sprae#32]
If there is a "slight" problem with the priority of directives (for example, each and text), then perhaps it is necessary not only to read all the attributes in a row, but also to add the priority of reading.

**Comment by dy** [comment]
Depends on your case.

Generally priority is defined by order of directives on a tag, so you should be considerate about it. That's in the readme#hints section.

That's the nature of sprae engine, there used to be primary/secondary directive groups, which proved to be foolproof but unnecessary.

So if you show convincing use-case I can reconsider, but so far some mental exercise of properly ordering directives seems to be healthy.

**Comment by vanodevium** [comment]
@dy 

Sounds convincing.

Unless, in my opinion, it should be raised from the hints exactly to each directive, so that it immediately catches the eye and it is clear that if it does not work - most likely, the user specified it in the wrong order.

**Comment by dy** [comment]
I added a little note in :each description.
