### ISSUE TITLE
Question: innerHTML

### ISSUE THREAD

**Issue by vanodevium** [dy/sprae#41]
Is there a directive or option to specify the inner html of an element if, for example, that "content" is stored in a global variable?

**Comment by dy** [comment]
Can you give an example?

**Comment by vanodevium** [comment]
@dy 

I have an element **div#modal**.
On page initiation it has innerHTML:

```html
div#modal-header
div#modal-content
div#modal-footer
```

But after some user actions I have to change this content. 

So, if i correctly understand, I have to change some variable and then **div#modal** will change it's innerHTML reactively

**Comment by dy** [comment]
usually I either put :if condition or :hidden flag. If you need whole html content to be taken from somewhere else either use :ref=el :fx=el.innerHTML=str, or :html=otherElement

**Comment by vanodevium** [comment]
Ok. Thanx!
