### ISSUE TITLE
[Bug] directive :value can't use with "justin"

### ISSUE THREAD

**Issue by khanhicetea** [dy/sprae#45]
Hi,

I tried to use the "justin" compile function, but looks like the directive :value has error on setValue.

Looks like the `evaluate.push(parse(`${expr}=arguments[1];`))` error because `arguments` doesn't exist when excute compiled function

Below is the console error

<img width="452" alt="image" src="https://github.com/user-attachments/assets/19ec4bd5-05f4-4100-a6c0-538b28dc99cb">

**Comment by dy** [comment]
Good catch! let me fix it

**Comment by dy** [comment]
Ok, fixed `:value` case. Not the most concise solution, but works.
