### ISSUE TITLE
Loop inside a loop not working

### ISSUE THREAD

**Issue by MasterPuffin** [dy/sprae#47]
I experience the following issue:
When I put a loop inside a loop it does not render. For example
```
<div class="container py-4">
    <div class="row" id="container">
        <div class="col" :each="object in objects">
            <div class="card">
                <div class="card-body">
                    <span :text="object.m"/>
                    <div :each="field in fields">
                        <span :text="field.label"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
```
Renders the objects but not the fields

```
<div class="container py-4">
    <div class="row" id="container">
        <div class="col" :each="object in objects">
            <div class="card">
                <div class="card-body">
                    <span :text="object.m"/>
                </div>
            </div>
        </div>
        <div :each="field in fields">
        <span :text="field.label"/>
    </div>
    </div>
</div>
```
This one renders the objects and the fields, however I want the fields inside the objects.

**Comment by dy** [comment]
Is `objects`, `fields` array or object?

**Comment by dy** [comment]
Just tested with both arrays/objects, works as expected @MasterPuffin. Please provide more exact case with real data.

**Comment by MasterPuffin** [comment]
I tried objects and arrays, however the issue is not sprae, it's that I not used a separate end tag for the span element
'''
                    <span :text="object.m"/>
'''
won't work, is has to be
'''
                    <span :text="object.m"></span>
'''

**Comment by dy** [comment]
That's what I guessed, thanks @MasterPuffin

**Comment by dy** [comment]
@MasterPuffin but it seems `<span :text="x"/>` works fine on my side as well. I suspect there was a markup issue, like unclosed tag or something?
