### ISSUE TITLE
Function on :text

### ISSUE THREAD

**Issue by MasterPuffin** [dy/sprae#49]
I want to use a function to format a text, for example
```
<p :text="()=>{formatVal(object[field.name])}"></p>
```
however, this renders `()=>{formatVal(object[field.name])}` and not the return value of the function.

**Comment by dy** [comment]
I can see a few ways
1. `<p :with="{formatted: formatVal(object[field.name})}" :text="formatted"></p>`
2. `sprae(el, { object:..., get formatted(){ return formatVal(this.object[field.name]) } })`
3. `let formatted = computed(()=>formatVal(object[field.name])); sprae(el, { object, formatted })`
4. `<p :text="computed(() => formatVal(object[field.name]))"></p>`, `import {computed} from 'sprae'; sprae(el, {..., computed})`

But - possibly that's good idea to autowrap function props into computed. 
Please let me know if you find other situations when you need it, if there's 2-3 use-cases I can try to add it

**Comment by MasterPuffin** [comment]
It would be very useful for inline edits, eg. a display of values which can be toggled to inputs. 
One scenario would be rendering of numbers. Numbers are stored without trailing zeroes which makes displaying for example prices not pretty.
Also to display the label of a select field. The value would be a storable value, but if I want to display the corresponding label I could access it via a function call.

**Comment by dy** [comment]
@MasterPuffin which of this cases cannot be solved with just `:text="formatVal(object[field.name])"`? I wonder what's the purpose of specifically function here `:text="() => formatVal(object[field.name])"`

**Comment by MasterPuffin** [comment]
Sorry I was confused, I thought that passing parameters this way is not possible, like described in my issue here https://github.com/dy/sprae/issues/46

**Comment by dy** [comment]
Yes, essentially attribute receives exactly the value you pass: for `:onclick` that must be a function, for `:attr` that must be a string/number/etc.
