### ISSUE TITLE
Bench compare to lit and petite-vue

### ISSUE THREAD

**Issue by aelbore** [dy/sprae#8]
@dy cool project thanks for this, im doing some side projects using this library👍

Do you have plan to have benchmark compare to lit and petite-vue? 

thanks

**Comment by dy** [comment]
Yeah, that's last thing remaining in plan. If you have some particular input for what you're curious to benchmark.

**Comment by aelbore** [comment]
@dy thanks for the response 
maybe include on this benchmark?

https://github.com/krausest/js-framework-benchmark

**Comment by dy** [comment]
So comparison with lit, petite-vue, alpine:
<img width="370" alt="image" src="https://github.com/dy/sprae/assets/300067/836b1345-02ef-4cc4-8a3c-b0f1aa273ae2">
<img width="446" alt="image" src="https://github.com/dy/sprae/assets/300067/35d639a7-7957-43a2-b17a-55a7215e1607">
It seems there's potential memory leak or inefficient use of store.
I will try switching back to signals store and see if it improves metrics / fixes leak.

**Comment by dy** [comment]
Also it seems there's a chance to improve DOM swapping. I use more robust but less quick version.

**Comment by dy** [comment]
Preliminary result doesn't show any significant perf improvement for signals state over proxy. Maybe should consider instead of signals store to just make proxy support signals
<img width="368" alt="image" src="https://github.com/dy/sprae/assets/300067/b122e14a-0484-48b8-9a76-80bf52949e49">

**Comment by dy** [comment]
Ok, check https://krausest.github.io/js-framework-benchmark/2023/table_chrome_120.0.6099.62.html - sprae is better than petite-vue in almost all metrics.
