### ISSUE TITLE
use signals as state management

### ISSUE THREAD

**Issue by aelbore** [dy/sprae#9]
Hey @dy this library is cool :) 

I know this has built-in state management, I have existing state management that uses signals, 
for example I want to use this as View only and use my existing store as Controller or Model does this possible? if yes do I need to access the `.value` of the signal/computed property in the html? thanks

**Comment by dy** [comment]
It used to be built with signals store https://www.npmjs.com/package/signal-struct but then it was replaced in favor of more compact & flexible proxy-based one. 
Let me check if it's possible to support signals as dynamic sources.
Do you have an example of your store?

**Comment by aelbore** [comment]
```javascript 
import { signal } from 'usignal'
import { createStore } from 'signal-store'

// state is not accessible, need to use actions to update the state
// getters is accessible 
const store = createStore({
  state: {
    count: signal(0)
  },
  getters: {
    count(state) {
      return state.count.value
    }
  },
  actions: {
    increment({ state }, count: number) {
      state.count.value = state.count.peek() + 1
    },
    decrement({ state }, count: number) {
      state.count.value = state.count.peek() + 1
    }
  }
})
```

**Comment by dy** [comment]
Is that store essentially same as just object with signals as keys? In other words, you'd want to use signals directly as template values?

**Comment by aelbore** [comment]
> Is that store essentially same as just object with signals as keys?
yes

 In other words, you'd want to use signals directly as template values?
yes correct

because I don't want o rewrite the store that I created or I want reuse the reactive values and functions

**Comment by dy** [comment]
ok, will try to see if it makes sense to switch store back to signals. It's less compact but possibly faster
